apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongodb-charts.fullname" . }}
  labels:
{{ include "mongodb-charts.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mongodb-charts.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mongodb-charts.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: keys
          persistentVolumeClaim:
            claimName: keys
            emptyDir: {}
        - name: web
          persistentVolumeClaim:
            claimName: web
            emptyDir: {}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "mongodb-charts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          lifecycle:
            postStart:
              exec:
                command: ['sh', '-c', 'charts-cli add-user --first-name "O" --last-name "R" --email "noone@gmail.com" --password "usera_!" --role "UserAdmin"']
          env: 
            - name: CHARTS_SUPPORT_WIDGET_AND_METRICS
              value: "off"
            - name: CHARTS_MONGODB_URI
              value: mongodb://pythoncoderr:azxcf123456@12.200.77.77:27018/admin
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: keys
              mountPath: /mongodb-charts/volumes/keys/
            - name: web
              mountPath: /mongodb-charts/volumes/www/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
