{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mongodb-charts.serviceAccountName" . }}
  labels:
{{ include "mongodb-charts.labels" . | indent 4 }}
{{- end -}}
